[DEFAULT]
PRODUCT_NAME = events

AUTO_DEPLOY = true
GITHUB_REPO_NAME = ala-events
GITHUB_OWNER = AtlasOfLivingAustralia
REGION = ap-southeast-2

# the bootstrap stack names. These are used by the codepipeline stacks to import
# the codepipeline roles, buckets and codestar connections
BOOTSTRAP_STACK_NAME = ala-bedrock-cicd-bootstrap-production
BUCKETS_STACK_NAME = ala-bedrock-cicd-buckets-production
VPC_STACK_NAME = ala-bedrock-vpc-production
COGNITO_STACK_NAME = ala-cognito-pool-production

# futher messy solutions 
US_EAST_ARTIFACT_BUCKET=ala-code-pipeline-artifacts-${AWS_ACCOUNT_ID}-us-east-1-production

# the app stacks
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${ENVIRONMENT}
ECR_STACK_NAME = ala-${PRODUCT_NAME}-ecr-${ENVIRONMENT}

ALA_SECRETS_NAME=ala-secrets-production

IMAGE_NAME=ala-${PRODUCT_NAME}
IMAGE_TAG=latest

WS_SUB_DOMAIN = service
UI_SUB_DOMAIN = ${PRODUCT_NAME}

[development]
COGNITO_STACK_NAME = ala-cognito-pool-production

BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${CLEAN_BRANCH}
ECR_STACK_NAME = ala-${PRODUCT_NAME}-ecr-${CLEAN_BRANCH}

HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c
CLOUDFRONT_CERTIFICATE = arn:aws:acm:us-east-1:736913556139:certificate/4b62cca2-9daf-4e38-b01a-48271ab3311a

REGOLITH_STACK_NAME = ala-regolith-cluster-production

WS_SUB_DOMAIN = ${CLEAN_BRANCH}-service
UI_SUB_DOMAIN = ${PRODUCT_NAME}-${CLEAN_BRANCH}

[testing]
HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c
CLOUDFRONT_CERTIFICATE = arn:aws:acm:us-east-1:736913556139:certificate/4b62cca2-9daf-4e38-b01a-48271ab3311a

REGOLITH_STACK_NAME = ala-regolith-cluster-production

WS_SUB_DOMAIN = ${CLEAN_BRANCH}-service
UI_SUB_DOMAIN = ${PRODUCT_NAME}-${CLEAN_BRANCH}

[staging]
HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c
CLOUDFRONT_CERTIFICATE = arn:aws:acm:us-east-1:736913556139:certificate/4b62cca2-9daf-4e38-b01a-48271ab3311a

REGOLITH_STACK_NAME = ala-regolith-cluster-staging

WS_SUB_DOMAIN = staging-service
UI_SUB_DOMAIN = ${PRODUCT_NAME}-staging

[production]
AUTO_DEPLOY = false

HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c
CLOUDFRONT_CERTIFICATE = arn:aws:acm:us-east-1:736913556139:certificate/4b62cca2-9daf-4e38-b01a-48271ab3311a

REGOLITH_STACK_NAME = ala-regolith-cluster-production