Project:
  Name: ALA-events
  Stage: dev

Stack:
  EventsAPI:
    Name: API
    Parameters:
      domain: 
        zoneId: Z0205454134UILBVG0TC
        zoneName: dev.ala.org.au
  EventsUI:
    Name: UI
    Parameters:
      domain: 
        zoneId: Z0205454134UILBVG0TC
        zoneName: dev.ala.org.au
        domainName: events.dev.ala.org.au
        certificateArn: arn:aws:acm:us-east-1:748909248546:certificate/44fe9e04-6511-4a46-a0b8-36209d443f21
  EventsAPIPipeline:
    Name: API-Pipeline
    Parameters:
      connectionArn: arn:aws:codestar-connections:ap-southeast-2:748909248546:connection/e336fd41-54c2-42e1-97c9-cbd6cc09fe88
      owner: AtlasOfLivingAustralia
      repo: ala-events
      branch: epic/cicd/develop
  EventsEks:
    Name: EKS
    Parameters:
      clusterName: testing
  Pipeline:
    Name: UI-Pipeline
    Parameters:
      connectionArn: arn:aws:codestar-connections:ap-southeast-2:748909248546:connection/e336fd41-54c2-42e1-97c9-cbd6cc09fe88
      owner: AtlasOfLivingAustralia
      repo: ala-events
      branch: epic/cicd/develop

      