Project:
  Name: ALA-events
  Stage: test

Stack:
  EventsUI:
    Name: UI
    Parameters:
      # domain: 
      #   zoneId: Z0788991HA5BZCF09QS3
      #   domainName: events.test.ala.org.au
      #   certificateArn: arn:aws:acm:us-east-1:748909248546:certificate/dd739e47-f989-4181-ad28-34518473eff4
  Pipeline:
    Name: Pipeline
    Parameters:
      connectionArn: arn:aws:codestar-connections:ap-southeast-2:748909248546:connection/e336fd41-54c2-42e1-97c9-cbd6cc09fe88
      owner: AtlasOfLivingAustralia
      repo: ala-events
      branch: epic/cicd/develop

      