apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ala-events.fullname" . }}-es-api
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
spec:
  replicas: {{ .Values.esApi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "ala-events.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
  template:
    metadata:
      annotations:
        checksum/configs: {{ .Values.deploymentChecksum | quote }}
        commitHash: {{ .Values.commitHash | quote }}
      labels:
        {{- include "ala-events.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-es-api
          image: "{{ .Values.esApi.image.repository }}:{{ .Values.esApi.image.tag }}"
          imagePullPolicy: {{ .Values.esApi.image.pullPolicy }}
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          ports:
            - containerPort: 4001
          resources:
            {{- toYaml .Values.esApi.resources | nindent 12 }}
          {{- include "ala-events.probes" .Values.esApi | nindent 10 }}
          volumeMounts:
            - name: events-config
              mountPath: /usr/src/.env
              subPath: es-api.env
      volumes:
        - name: events-config
          configMap:
            name: {{ include "ala-events.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ala-events.fullname" . }}-es2vt
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es2vt
spec:
  replicas: {{ .Values.es2vt.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "ala-events.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es2vt
  template:
    metadata:
      annotations:
        checksum/configs: {{ .Values.deploymentChecksum | quote }}
        commitHash: {{ .Values.commitHash | quote }}
      labels:
        {{- include "ala-events.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es2vt
    spec:
      containers:
      - name: {{ .Chart.Name }}-es2vt
        image: "{{ .Values.es2vt.image.repository }}:{{ .Values.es2vt.image.tag }}"
        env:
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
        ports:
        - containerPort: 4002
        resources:
          {{- toYaml .Values.es2vt.resources | nindent 10 }}
        {{- include "ala-events.probes" .Values.es2vt | nindent 8 }}
        volumeMounts:
        - name: events-config
          mountPath: /usr/src/.env
          subPath: es2vt.env
      volumes:
        - name: events-config
          configMap:
            name: {{ include "ala-events.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ala-events.fullname" . }}-graphql-api
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-graphql-api
spec:
  replicas: {{ .Values.graphqlApi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "ala-events.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-graphql-api
  template:
    metadata:
      annotations:
        checksum/configs: {{ .Values.deploymentChecksum | quote }}
        commitHash: {{ .Values.commitHash | quote }}
      labels:
        {{- include "ala-events.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-graphql-api
    spec:
      containers:
      - name: {{ .Chart.Name }}-graphql-api
        image: "{{ .Values.graphqlApi.image.repository }}:{{ .Values.graphqlApi.image.tag }}"
        ports:
        - containerPort: 4000
        resources:
          {{- toYaml .Values.graphqlApi.resources | nindent 10 }}
        {{- include "ala-events.probes" .Values.graphqlApi | nindent 8 }}
        volumeMounts:
        - name: events-config
          mountPath: /usr/src/.env
          subPath: graphql-api.env
      volumes:
        - name: events-config
          configMap:
            name: {{ include "ala-events.fullname" . }}