apiVersion: v1
kind: Service
metadata:
  name: {{ include "ala-events.fullname" . }}-es-api-service
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
spec:
  type: {{ .Values.esApi.service.type }}
  ports:
    - port: {{ .Values.esApi.service.port }}
      targetPort: {{ .Values.esApi.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-events.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ala-events.fullname" . }}-es2vt-service
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es2vt
spec:
  type: {{ .Values.es2vt.service.type }}
  ports:
    - port: {{ .Values.es2vt.service.port }}
      targetPort: {{ .Values.es2vt.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-events.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es2vt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ala-events.fullname" . }}-graphql-api-service
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-graphql-api
spec:
  type: {{ .Values.graphqlApi.service.type }}
  ports:
    - port: {{ .Values.graphqlApi.service.port }}
      targetPort: {{ .Values.graphqlApi.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-events.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-graphql-api