apiVersion: v1
kind: Service
metadata:
  name: {{ include "ala-events.fullname" . }}-es-api-service
  labels:
    {{- include "ala-events.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-events.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ala-events.fullname" . }}-es-api