version: 0.2
###
# This build project builds the events sub services - es, es2vt and graphql and pushes the Docker images
# to Amazon ECR

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    DOCKER_PASSWORD: $ALA_SECRETS_NAME:dockerhub-password
  exported-variables:
    - BUILD_TAG_ES_API
    - BUILD_TAG_ES2VT
    - BUILD_TAG_GRAPHQL_API
phases:
  install:
    commands:
      - echo Registering QEMU emulators for cross-platform builds...
      - docker run --rm --privileged public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v9.2.2 --install all
      - docker buildx version
      - docker buildx create --use --name multiarch-builder
      - echo Logging in to Docker Hub to avoid pull rate limits...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      - echo Build started on $(date)
      - |
        SERVICES=("es-api" "es2vt" "graphql-api")
        for SERVICE in "${SERVICES[@]}"; do
          BUILD_TAG="$SERVICE-$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER"
          UPPER=$(echo "$SERVICE" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
          echo "BUILD_TAG_${UPPER}=$BUILD_TAG" >> build.env
          export "BUILD_TAG_${UPPER}=${BUILD_TAG}"
          echo "Building and pushing the multi-arch Docker image for $SERVICE to ECR..."
          docker buildx build --platform linux/amd64,linux/arm64 \
                              -f "packages/$SERVICE/Dockerfile" \
                              -t "$ECR_REPO:$BUILD_TAG" \
                              -t "$ECR_REPO:$SERVICE-$IMAGE_TAG" \
                              --push \
                              "packages/$SERVICE"
        done

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)

artifacts:
  files:
    - build.env
