version: 0.2
###
# This build project builds the LISTS site files ready for upload to s3

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - cp events-ui/vite.properties events-ui/.env
      - echo injecting app client config
      - sed -i "s/VITE_AUTH_CLIENT_ID=.*$/VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID/g" events-ui/config/.env.$ENVIRONMENT
      - cat events-ui/config/.env.$ENVIRONMENT
      - cd packages/react-components
  pre_build:
    commands:
      - echo running npm install...
      - npm i
  build:
    commands:
      - echo building...
      - npm run build:$ENVIRONMENT

artifacts:
  base-directory: packages/react-components/dist
  files:
    - '**/*'
