version: 0.2
###
# This build project builds the Events site files ready for upload to s3

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - TODO create .evn.json and config.js
#      - cp events-ui/vite.properties events-ui/.env
#      - echo injecting app client config
#      - sed -i "s/VITE_AUTH_CLIENT_ID=.*$/VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID/g" events-ui/config/.env.$ENVIRONMENT
#      - cat events-ui/config/.env.$ENVIRONMENT
  pre_build:
    commands:
      - cd packages/react-components
      - npm install
  build:
    commands:
      - npm run build-translations
      - npm run build

artifacts:
  base-directory: packages/react-components
  files:
    - 'ala-demo.html'
    - 'config.js'
    - 'dist/**/*'
