[DEFAULT]
PRODUCT_COMPONENT = backend
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
HELM_RELEASE_NAME = ala-events-${ENVIRONMENT}
EKS_NAMESPACE = apps

AUTO_DEPLOY = true
SLACK_DEPLOY_NOTIFICATION = true
SLACK_ALERT_CHANNEL = zabbix-alerts

DOCKER_USERNAME = systems@ala.org.au

API_DOWNLOAD = https://api.ala.org.au/dataset/{datasetKey}
DATASET_EML = https://collections.ala.org.au/ws/eml/{datasetKey}
BIE_URL = https://bie-ws.ala.org.au/ws
BIOCACHE_URL = https://biocache-ws.ala.org.au
IMAGES_URL = https://images.ala.org.au
NAMEMATCHING_URL = https://namematching-ws.ala.org.au/
ELASTIC_HOST = elasticsearch-${ENVIRONMENT}
ELASTIC_PORT = 9200
ES_INDEX = event

ELASTICSEARCH_USERNAME=elastic
ELASTICSEARCH_AUTH_ENABLED=true
ELASTICSEARCH_ENDPOINT=${CLEAN_BRANCH}-cluster-es-http.elasticsearch.svc.cluster.local
ELASTICSEARCH_SECRET_NAME = ala-regolith-${CLEAN_BRANCH}-elasticsearch

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}

HELM_RELEASE_NAME = ala-events-${CLEAN_BRANCH}

API_DOWNLOAD = https://api.test.ala.org.au/dataset/{datasetKey}
DATASET_EML = https://collections-test.ala.org.au/ws/eml/{datasetKey}
BIOCACHE_URL = https://biocache-ws-test.ala.org.au
BIE_URL = https://bie-ws-test.ala.org.au/ws
IMAGES_URL = https://images.test.ala.org.au
NAMEMATCHING_URL = https://namematching-ws-test.ala.org.au/
ELASTIC_HOST = elasticsearch-${CLEAN_BRANCH}
ES_INDEX = event-databox
ELASTICSEARCH_USERNAME=elastic
ELASTICSEARCH_AUTH_ENABLED=false
ELASTICSEARCH_TLS_ENABLED=false
ELASTICSEARCH_ENDPOINT=elasticsearch-${CLEAN_BRANCH}

[testing]

API_DOWNLOAD = https://api.test.ala.org.au/dataset/{datasetKey}
DATASET_EML = https://collections-test.ala.org.au/ws/eml/{datasetKey}
BIOCACHE_URL = https://biocache-ws-test.ala.org.au
BIE_URL = https://bie-ws-test.ala.org.au/ws
IMAGES_URL = https://images.test.ala.org.au
NAMEMATCHING_URL = https://namematching-ws-test.ala.org.au/
EKS_NAMESPACE = events
ES_INDEX = event-databox

ELASTICSEARCH_ENDPOINT = main-cluster-es-http.elasticsearch.svc.cluster.local
ELASTICSEARCH_SECRET_NAME = ala-regolith-production-elasticsearch

[staging]


[production]

AUTO_DEPLOY = false
SLACK_ALERT_CHANNEL = deployments

ELASTICSEARCH_ENDPOINT = main-cluster-es-http.elasticsearch.svc.cluster.local
ELASTICSEARCH_SECRET_NAME = ala-regolith-production-elasticsearch