apiVersion: v1
kind: PersistentVolume
metadata:
  name: ala-events-elasticsearch-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fsap-04124cee2d7fc5b0e
  storageClassName: ""
  mountOptions:
    - tls