# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ala-events-elasticsearch-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce # Matches the PV's access mode
#   resources:
#     requests:
#       storage: 10Gi # Matches or is less than the PV's capacity
#   storageClassName: "" # Matches the PV's storage class (empty in this case)